const books = [
  {
    "id": 0,
    "title": "Things Fall Apart",
    "author": "Chinua Achebe",
    "country": "Nigeria",
    "img": "images/things-fall-apart.jpg",
    "year": 1958,
    "pages": 209,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    "add_bookmark": false
  },
  {
    "id": 1,
    "title": "Fairy tales",
    "author": "Hans Christian Andersen",
    "country": "Denmark",
    "img": "images/fairy-tales.jpg",
    "year": 1836,
    "pages": 784,
    "language": "Danish",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    "add_bookmark": false
  },
  {
    "id": 2,
    "title": "The Divine Comedy",
    "author": "Dante Alighieri",
    "country": "Italy",
    "img": "images/the-divine-comedy.jpg",
    "year": 1315,
    "pages": 928,
    "language": "Italian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    "add_bookmark": false
  },
  {
    "id": 3,
    "title": "The Epic Of Gilgamesh",
    "author": "Unknown",
    "country": "Sumer and Akkadian Empire",
    "img": "images/the-epic-of-gilgamesh.jpg",
    "year": -1700,
    "pages": 160,
    "language": "Akkadian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    "add_bookmark": false
  },
  {
    "id": 4,
    "title": "The Book Of Job",
    "author": "Unknown",
    "country": "Achaemenid Empire",
    "img": "images/the-book-of-job.jpg",
    "year": -600,
    "pages": 176,
    "language": "Hebrew",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
    "add_bookmark": false
  },
  {
    "id": 5,
    "title": "One Thousand and One Nights",
    "author": "Unknown",
    "country": "India/Iran/Iraq/Egypt/Tajikistan",
    "img": "images/one-thousand-and-one-nights.jpg",
    "year": 1200,
    "pages": 288,
    "language": "Arabic",
    "wikipedia_link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    "add_bookmark": false
  },
  {
    "id": 6,
    "title": "Njál's Saga",
    "author": "Unknown",
    "country": "Iceland",
    "img": "images/njals-saga.jpg",
    "year": 1350,
    "pages": 384,
    "language": "Old Norse",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    "add_bookmark": false
  },
  {
    "id": 7,
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "country": "United Kingdom",
    "img": "images/pride-and-prejudice.jpg",
    "year": 1813,
    "pages": 226,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    "add_bookmark": false
  },
  {
    "id": 8,
    "title": "Le Père Goriot",
    "author": "Honoré de Balzac",
    "country": "France",
    "img": "images/le-pere-goriot.jpg",
    "year": 1835,
    "pages": 443,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    "add_bookmark": false
  },
  {
    "id": 9,
    "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
    "author": "Samuel Beckett",
    "country": "Republic of Ireland",
    "img": "images/molloy-malone-dies-the-unnamable.jpg",
    "year": 1952,
    "pages": 256,
    "language": "French, English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    "add_bookmark": false
  },
  {
    "id": 10,
    "title": "Ficciones",
    "author": "Jorge Luis Borges",
    "country": "Argentina",
    "img": "images/ficciones.jpg",
    "year": 1965,
    "pages": 224,
    "language": "Spanish",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Ficciones\n",
    "add_bookmark": false
  },
  {
    "id": 11,
    "title": "Wuthering Heights",
    "author": "Emily Brontë",
    "country": "United Kingdom",
    "img": "images/wuthering-heights.jpg",
    "year": 1847,
    "pages": 342,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    "add_bookmark": false
  },
  {
    "id": 12,
    "title": "The Stranger",
    "author": "Albert Camus",
    "country": "Algeria, French Empire",
    "img": "images/l-etranger.jpg",
    "year": 1942,
    "pages": 185,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    "add_bookmark": false
  },
  {
    "id": 13,
    "title": "Poems",
    "author": "Paul Celan",
    "country": "Romania, France",
    "img": "images/poems-paul-celan.jpg",
    "year": 1952,
    "pages": 320,
    "language": "German",
    "wikipedia_link": "\n",
    "add_bookmark": false
  },
  {
    "id": 14,
    "title": "Journey to the End of the Night",
    "author": "Louis-Ferdinand Céline",
    "country": "France",
    "img": "images/voyage-au-bout-de-la-nuit.jpg",
    "year": 1932,
    "pages": 505,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    "add_bookmark": false
  },
  {
    "id": 15,
    "title": "Don Quijote De La Mancha",
    "author": "Miguel de Cervantes",
    "country": "Spain",
    "img": "images/don-quijote-de-la-mancha.jpg",
    "year": 1610,
    "pages": 1056,
    "language": "Spanish",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
    "add_bookmark": false
  },
  {
    "id": 16,
    "title": "The Canterbury Tales",
    "author": "Geoffrey Chaucer",
    "country": "England",
    "img": "images/the-canterbury-tales.jpg",
    "year": 1450,
    "pages": 544,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    "add_bookmark": false
  },
  {
    "id": 17,
    "title": "Stories",
    "author": "Anton Chekhov",
    "country": "Russia",
    "img": "images/stories-of-anton-chekhov.jpg",
    "year": 1886,
    "pages": 194,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    "add_bookmark": false
  },
  {
    "id": 18,
    "title": "Nostromo",
    "author": "Joseph Conrad",
    "country": "United Kingdom",
    "img": "images/nostromo.jpg",
    "year": 1904,
    "pages": 320,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Nostromo\n",
    "add_bookmark": false
  },
  {
    "id": 19,
    "title": "Great Expectations",
    "author": "Charles Dickens",
    "country": "United Kingdom",
    "img": "images/great-expectations.jpg",
    "year": 1861,
    "pages": 194,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
    "add_bookmark": false
  },
  {
    "id": 20,
    "title": "Jacques the Fatalist",
    "author": "Denis Diderot",
    "country": "France",
    "img": "images/jacques-the-fatalist.jpg",
    "year": 1796,
    "pages": 596,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
    "add_bookmark": false
  },
  {
    "id": 21,
    "title": "Berlin Alexanderplatz",
    "author": "Alfred Döblin",
    "country": "Germany",
    "img": "images/berlin-alexanderplatz.jpg",
    "year": 1929,
    "pages": 600,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
    "add_bookmark": false
  },
  {
    "id": 22,
    "title": "Crime and Punishment",
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "img": "images/crime-and-punishment.jpg",
    "year": 1866,
    "pages": 551,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
    "add_bookmark": false
  },
  {
    "id": 23,
    "title": "The Idiot",
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "img": "images/the-idiot.jpg",
    "year": 1869,
    "pages": 656,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Idiot\n",
    "add_bookmark": false
  },
  {
    "id": 24,
    "title": "The Possessed",
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "img": "images/the-possessed.jpg",
    "year": 1872,
    "pages": 768,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
    "add_bookmark": false
  },
  {
    "id": 25,
    "title": "The Brothers Karamazov",
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "img": "images/the-brothers-karamazov.jpg",
    "year": 1880,
    "pages": 824,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
    "add_bookmark": false
  },
  {
    "id": 26,
    "title": "Middlemarch",
    "author": "George Eliot",
    "country": "United Kingdom",
    "img": "images/middlemarch.jpg",
    "year": 1871,
    "pages": 800,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Middlemarch\n",
    "add_bookmark": false
  },
  {
    "id": 27,
    "title": "Invisible Man",
    "author": "Ralph Ellison",
    "country": "United States",
    "img": "images/invisible-man.jpg",
    "year": 1952,
    "pages": 581,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Invisible_Man\n",
    "add_bookmark": false
  },
  {
    "id": 28,
    "title": "Medea",
    "author": "Euripides",
    "country": "Greece",
    "img": "images/medea.jpg",
    "year": -431,
    "pages": 104,
    "language": "Greek",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Medea_(play)\n",
    "add_bookmark": false
  },
  {
    "id": 29,
    "title": "Absalom, Absalom!",
    "author": "William Faulkner",
    "country": "United States",
    "img": "images/absalom-absalom.jpg",
    "year": 1936,
    "pages": 313,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
    "add_bookmark": false
  },
  {
    "id": 30,
    "title": "The Sound and the Fury",
    "author": "William Faulkner",
    "country": "United States",
    "img": "images/the-sound-and-the-fury.jpg",
    "year": 1929,
    "pages": 326,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
    "add_bookmark": false
  },
  {
    "id": 31,
    "title": "Madame Bovary",
    "author": "Gustave Flaubert",
    "country": "France",
    "img": "images/madame-bovary.jpg",
    "year": 1857,
    "pages": 528,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Madame_Bovary\n",
    "add_bookmark": false
  },
  {
    "id": 32,
    "title": "Sentimental Education",
    "author": "Gustave Flaubert",
    "country": "France",
    "img": "images/l-education-sentimentale.jpg",
    "year": 1869,
    "pages": 606,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Sentimental_Education\n",
    "add_bookmark": false
  },
  {
    "id": 33,
    "title": "Gypsy Ballads",
    "author": "Federico García Lorca",
    "country": "Spain",
    "img": "images/gypsy-ballads.jpg",
    "year": 1928,
    "pages": 218,
    "language": "Spanish",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Gypsy_Ballads\n",
    "add_bookmark": false
  },
  {
    "id": 34,
    "title": "One Hundred Years of Solitude",
    "author": "Gabriel García Márquez",
    "country": "Colombia",
    "img": "images/one-hundred-years-of-solitude.jpg",
    "year": 1967,
    "pages": 417,
    "language": "Spanish",
    "wikipedia_link": "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
    "add_bookmark": false
  },
  {
    "id": 35,
    "title": "Love in the Time of Cholera",
    "author": "Gabriel García Márquez",
    "country": "Colombia",
    "img": "images/love-in-the-time-of-cholera.jpg",
    "year": 1985,
    "pages": 368,
    "language": "Spanish",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
    "add_bookmark": false
  },
  {
    "id": 36,
    "title": "Faust",
    "author": "Johann Wolfgang von Goethe",
    "country": "Saxe-Weimar",
    "img": "images/faust.jpg",
    "year": 1832,
    "pages": 158,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
    "add_bookmark": false
  },
  {
    "id": 37,
    "title": "Dead Souls",
    "author": "Nikolai Gogol",
    "country": "Russia",
    "img": "images/dead-souls.jpg",
    "year": 1842,
    "pages": 432,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Dead_Souls\n",
    "add_bookmark": false
  },
  {
    "id": 38,
    "title": "The Tin Drum",
    "author": "Günter Grass",
    "country": "Germany",
    "img": "images/the-tin-drum.jpg",
    "year": 1959,
    "pages": 600,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
    "add_bookmark": false
  },
  {
    "id": 39,
    "title": "The Devil to Pay in the Backlands",
    "author": "João Guimarães Rosa",
    "country": "Brazil",
    "img": "images/the-devil-to-pay-in-the-backlands.jpg",
    "year": 1956,
    "pages": 494,
    "language": "Portuguese",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
    "add_bookmark": false
  },
  {
    "id": 40,
    "title": "Hunger",
    "author": "Knut Hamsun",
    "country": "Norway",
    "img": "images/hunger.jpg",
    "year": 1890,
    "pages": 176,
    "language": "Norwegian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
    "add_bookmark": false
  },
  {
    "id": 41,
    "title": "The Old Man and the Sea",
    "author": "Ernest Hemingway",
    "country": "United States",
    "img": "images/the-old-man-and-the-sea.jpg",
    "year": 1952,
    "pages": 128,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
    "add_bookmark": false
  },
  {
    "id": 42,
    "title": "Iliad",
    "author": "Homer",
    "country": "Greece",
    "img": "images/the-iliad-of-homer.jpg",
    "year": -735,
    "pages": 608,
    "language": "Greek",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Iliad\n",
    "add_bookmark": false
  },
  {
    "id": 43,
    "title": "Odyssey",
    "author": "Homer",
    "country": "Greece",
    "img": "images/the-odyssey-of-homer.jpg",
    "year": -800,
    "pages": 374,
    "language": "Greek",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Odyssey\n",
    "add_bookmark": false
  },
  {
    "id": 44,
    "title": "A Doll's House",
    "author": "Henrik Ibsen",
    "country": "Norway",
    "img": "images/a-Dolls-house.jpg",
    "year": 1879,
    "pages": 68,
    "language": "Norwegian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
    "add_bookmark": false
  },
  {
    "id": 45,
    "title": "Ulysses",
    "author": "James Joyce",
    "country": "Irish Free State",
    "img": "images/ulysses.jpg",
    "year": 1922,
    "pages": 228,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
    "add_bookmark": false
  },
  {
    "id": 46,
    "title": "Stories",
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "img": "images/stories-of-franz-kafka.jpg",
    "year": 1924,
    "pages": 488,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
    "add_bookmark": false
  },
  {
    "id": 47,
    "title": "The Trial",
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "img": "images/the-trial.jpg",
    "year": 1925,
    "pages": 160,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Trial\n",
    "add_bookmark": false
  },
  {
    "id": 48,
    "title": "The Castle",
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "img": "images/the-castle.jpg",
    "year": 1926,
    "pages": 352,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
    "add_bookmark": false
  },
  {
    "id": 49,
    "title": "The recognition of Shakuntala",
    "author": "Kālidāsa",
    "country": "India",
    "img": "images/the-recognition-of-shakuntala.jpg",
    "year": 150,
    "pages": 147,
    "language": "Sanskrit",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
    "add_bookmark": false
  },
  {
    "id": 50,
    "title": "The Sound of the Mountain",
    "author": "Yasunari Kawabata",
    "country": "Japan",
    "img": "images/the-sound-of-the-mountain.jpg",
    "year": 1954,
    "pages": 288,
    "language": "Japanese",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
    "add_bookmark": false
  },
  {
    "id": 51,
    "title": "Zorba the Greek",
    "author": "Nikos Kazantzakis",
    "country": "Greece",
    "img": "images/zorba-the-greek.jpg",
    "year": 1946,
    "pages": 368,
    "language": "Greek",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Zorba_the_Greek\n",
    "add_bookmark": false
  },
  {
    "id": 52,
    "title": "Sons and Lovers",
    "author": "D. H. Lawrence",
    "country": "United Kingdom",
    "img": "images/sons-and-lovers.jpg",
    "year": 1913,
    "pages": 432,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
    "add_bookmark": false
  },
  {
    "id": 53,
    "title": "Independent People",
    "author": "Halldór Laxness",
    "country": "Iceland",
    "img": "images/independent-people.jpg",
    "year": 1934,
    "pages": 470,
    "language": "Icelandic",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Independent_People\n",
    "add_bookmark": false
  },
  {
    "id": 54,
    "title": "Poems",
    "author": "Giacomo Leopardi",
    "country": "Italy",
    "img": "images/poems-giacomo-leopardi.jpg",
    "year": 1818,
    "pages": 184,
    "language": "Italian",
    "wikipedia_link": "\n",
    "add_bookmark": false
  },
  {
    "id": 55,
    "title": "The Golden Notebook",
    "author": "Doris Lessing",
    "country": "United Kingdom",
    "img": "images/the-golden-notebook.jpg",
    "year": 1962,
    "pages": 688,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Golden_Notebook\n",
    "add_bookmark": false
  },
  {
    "id": 56,
    "title": "Pippi Longstocking",
    "author": "Astrid Lindgren",
    "country": "Sweden",
    "img": "images/pippi-longstocking.jpg",
    "year": 1945,
    "pages": 160,
    "language": "Swedish",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Pippi_Longstocking\n",
    "add_bookmark": false
  },
  {
    "id": 57,
    "title": "Diary of a Madman",
    "author": "Lu Xun",
    "country": "China",
    "img": "images/diary-of-a-madman.jpg",
    "year": 1918,
    "pages": 389,
    "language": "Chinese",
    "wikipedia_link": "https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n",
    "add_bookmark": false
  },
  {
    "id": 58,
    "title": "Children of Gebelawi",
    "author": "Naguib Mahfouz",
    "country": "Egypt",
    "img": "images/children-of-gebelawi.jpg",
    "year": 1959,
    "pages": 355,
    "language": "Arabic",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Children_of_Gebelawi\n",
    "add_bookmark": false
  },
  {
    "id": 59,
    "title": "Buddenbrooks",
    "author": "Thomas Mann",
    "country": "Germany",
    "img": "images/buddenbrooks.jpg",
    "year": 1901,
    "pages": 736,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Buddenbrooks\n",
    "add_bookmark": false
  },
  {
    "id": 60,
    "title": "The Magic Mountain",
    "author": "Thomas Mann",
    "country": "Germany",
    "img": "images/the-magic-mountain.jpg",
    "year": 1924,
    "pages": 720,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Magic_Mountain\n",
    "add_bookmark": false
  },
  {
    "id": 61,
    "title": "Moby Dick",
    "author": "Herman Melville",
    "country": "United States",
    "img": "images/moby-dick.jpg",
    "year": 1851,
    "pages": 378,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Moby-Dick\n",
    "add_bookmark": false
  },
  {
    "id": 62,
    "title": "Essays",
    "author": "Michel de Montaigne",
    "country": "France",
    "img": "images/essais.jpg",
    "year": 1595,
    "pages": 404,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
    "add_bookmark": false
  },
  {
    "id": 63,
    "title": "History",
    "author": "Elsa Morante",
    "country": "Italy",
    "img": "images/history.jpg",
    "year": 1974,
    "pages": 600,
    "language": "Italian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/History_(novel)\n",
    "add_bookmark": false
  },
  {
    "id": 64,
    "title": "Beloved",
    "author": "Toni Morrison",
    "country": "United States",
    "img": "images/beloved.jpg",
    "year": 1987,
    "pages": 321,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Beloved_(novel)\n",
    "add_bookmark": false
  },
  {
    "id": 65,
    "title": "The Tale of Genji",
    "author": "Murasaki Shikibu",
    "country": "Japan",
    "img": "images/the-tale-of-genji.jpg",
    "year": 1006,
    "pages": 1360,
    "language": "Japanese",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Tale_of_Genji\n",
    "add_bookmark": false
  },
  {
    "id": 66,
    "title": "The Man Without Qualities",
    "author": "Robert Musil",
    "country": "Austria",
    "img": "images/the-man-without-qualities.jpg",
    "year": 1931,
    "pages": 365,
    "language": "German",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n",
    "add_bookmark": false
  },
  {
    "id": 67,
    "title": "Lolita",
    "author": "Vladimir Nabokov",
    "country": "Russia/United States",
    "img": "images/lolita.jpg",
    "year": 1955,
    "pages": 317,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Lolita\n",
    "add_bookmark": false
  },
  {
    "id": 68,
    "title": "Nineteen Eighty-Four",
    "author": "George Orwell",
    "country": "United Kingdom",
    "img": "images/nineteen-eighty-four.jpg",
    "year": 1949,
    "pages": 272,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
    "add_bookmark": false
  },
  {
    "id": 69,
    "title": "Metamorphoses",
    "author": "Ovid",
    "country": "Roman Empire",
    "img": "images/the-metamorphoses-of-ovid.jpg",
    "year": 100,
    "pages": 576,
    "language": "Classical Latin",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Metamorphoses\n",
    "add_bookmark": false
  },
  {
    "id": 70,
    "title": "The Book of Disquiet",
    "author": "Fernando Pessoa",
    "country": "Portugal",
    "img": "images/the-book-of-disquiet.jpg",
    "year": 1928,
    "pages": 272,
    "language": "Portuguese",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Book_of_Disquiet\n",
    "add_bookmark": false
  },
  {
    "id": 71,
    "title": "Tales",
    "author": "Edgar Allan Poe",
    "country": "United States",
    "img": "images/tales-and-poems-of-edgar-allan-poe.jpg",
    "year": 1950,
    "pages": 842,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n",
    "add_bookmark": false
  },
  {
    "id": 72,
    "title": "In Search of Lost Time",
    "author": "Marcel Proust",
    "country": "France",
    "img": "images/a-la-recherche-du-temps-perdu.jpg",
    "year": 1920,
    "pages": 2408,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
    "add_bookmark": false
  },
  {
    "id": 73,
    "title": "Gargantua and Pantagruel",
    "author": "François Rabelais",
    "country": "France",
    "img": "images/gargantua-and-pantagruel.jpg",
    "year": 1533,
    "pages": 623,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n",
    "add_bookmark": false
  },
  {
    "id": 74,
    "title": "Pedro Páramo",
    "author": "Juan Rulfo",
    "country": "Mexico",
    "img": "images/pedro-paramo.jpg",
    "year": 1955,
    "pages": 124,
    "language": "Spanish",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo\n",
    "add_bookmark": false
  },
  {
    "id": 75,
    "title": "The Masnavi",
    "author": "Rumi",
    "country": "Sultanate of Rum",
    "img": "images/the-masnavi.jpg",
    "year": 1236,
    "pages": 438,
    "language": "Persian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Masnavi\n",
    "add_bookmark": false
  },
  {
    "id": 76,
    "title": "Midnight's Children",
    "author": "Salman Rushdie",
    "country": "United Kingdom, India",
    "img": "images/midnights-children.jpg",
    "year": 1981,
    "pages": 536,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Midnight%27s_Children\n",
    "add_bookmark": false
  },
  {
    "id": 77,
    "title": "Bostan",
    "author": "Saadi",
    "country": "Persia, Persian Empire",
    "img": "images/bostan.jpg",
    "year": 1257,
    "pages": 298,
    "language": "Persian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Bustan_(book)\n",
    "add_bookmark": false
  },
  {
    "id": 78,
    "title": "Season of Migration to the North",
    "author": "Tayeb Salih",
    "country": "Sudan",
    "img": "images/season-of-migration-to-the-north.jpg",
    "year": 1966,
    "pages": 139,
    "language": "Arabic",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North\n",
    "add_bookmark": false
  },
  {
    "id": 79,
    "title": "Blindness",
    "author": "José Saramago",
    "country": "Portugal",
    "img": "images/blindness.jpg",
    "year": 1995,
    "pages": 352,
    "language": "Portuguese",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Blindness_(novel)\n",
    "add_bookmark": false
  },
  {
    "id": 80,
    "title": "Hamlet",
    "author": "William Shakespeare",
    "country": "England",
    "img": "images/hamlet.jpg",
    "year": 1603,
    "pages": 432,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Hamlet\n",
    "add_bookmark": false
  },
  {
    "id": 81,
    "title": "King Lear",
    "author": "William Shakespeare",
    "country": "England",
    "img": "images/king-lear.jpg",
    "year": 1608,
    "pages": 384,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/King_Lear\n",
    "add_bookmark": false
  },
  {
    "id": 82,
    "title": "Othello",
    "author": "William Shakespeare",
    "country": "England",
    "img": "images/othello.jpg",
    "year": 1609,
    "pages": 314,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Othello\n",
    "add_bookmark": false
  },
  {
    "id": 83,
    "title": "Oedipus the King",
    "author": "Sophocles",
    "country": "Greece",
    "img": "images/oedipus-the-king.jpg",
    "year": -430,
    "pages": 88,
    "language": "Greek",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Oedipus_the_King\n",
    "add_bookmark": false
  },
  {
    "id": 84,
    "title": "The Red and the Black",
    "author": "Stendhal",
    "country": "France",
    "img": "images/le-rouge-et-le-noir.jpg",
    "year": 1830,
    "pages": 576,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Red_and_the_Black\n",
    "add_bookmark": false
  },
  {
    "id": 85,
    "title": "The Life And Opinions of Tristram Shandy",
    "author": "Laurence Sterne",
    "country": "England",
    "img": "images/the-life-and-opinions-of-tristram-shandy.jpg",
    "year": 1760,
    "pages": 640,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n",
    "add_bookmark": false
  },
  {
    "id": 86,
    "title": "Confessions of Zeno",
    "author": "Italo Svevo",
    "country": "Italy",
    "img": "images/confessions-of-zeno.jpg",
    "year": 1923,
    "pages": 412,
    "language": "Italian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
    "add_bookmark": false
  },
  {
    "id": 87,
    "title": "Gulliver's Travels",
    "author": "Jonathan Swift",
    "country": "Ireland",
    "img": "images/gullivers-travels.jpg",
    "year": 1726,
    "pages": 178,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n",
    "add_bookmark": false
  },
  {
    "id": 88,
    "title": "War and Peace",
    "author": "Leo Tolstoy",
    "country": "Russia",
    "img": "images/war-and-peace.jpg",
    "year": 1867,
    "pages": 1296,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/War_and_Peace\n",
    "add_bookmark": false
  },
  {
    "id": 89,
    "title": "Anna Karenina",
    "author": "Leo Tolstoy",
    "country": "Russia",
    "img": "images/anna-karenina.jpg",
    "year": 1877,
    "pages": 864,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Anna_Karenina\n",
    "add_bookmark": false
  },
  {
    "id": 90,
    "title": "The Death of Ivan Ilyich",
    "author": "Leo Tolstoy",
    "country": "Russia",
    "img": "images/the-death-of-ivan-ilyich.jpg",
    "year": 1886,
    "pages": 92,
    "language": "Russian",
    "wikipedia_link": "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich\n",
    "add_bookmark": false
  },
  {
    "id": 91,
    "title": "The Adventures of Huckleberry Finn",
    "author": "Mark Twain",
    "country": "United States",
    "img": "images/the-adventures-of-huckleberry-finn.jpg",
    "year": 1884,
    "pages": 224,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n",
    "add_bookmark": false
  },
  {
    "id": 92,
    "title": "Ramayana",
    "author": "Valmiki",
    "country": "India",
    "img": "images/ramayana.jpg",
    "year": -450,
    "pages": 152,
    "language": "Sanskrit",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Ramayana\n",
    "add_bookmark": false
  },
  {
    "id": 93,
    "title": "The Aeneid",
    "author": "Virgil",
    "country": "Roman Empire",
    "img": "images/the-aeneid.jpg",
    "year": -23,
    "pages": 442,
    "language": "Classical Latin",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Aeneid\n",
    "add_bookmark": false
  },
  {
    "id": 94,
    "title": "Mahabharata",
    "author": "Vyasa",
    "country": "India",
    "img": "images/the-mahab-harata.jpg",
    "year": -700,
    "pages": 276,
    "language": "Sanskrit",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Mahabharata\n",
    "add_bookmark": false
  },
  {
    "id": 95,
    "title": "Leaves of Grass",
    "author": "Walt Whitman",
    "country": "United States",
    "img": "images/leaves-of-grass.jpg",
    "year": 1855,
    "pages": 152,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Leaves_of_Grass\n",
    "add_bookmark": false
  },
  {
    "id": 96,
    "title": "Mrs Dalloway",
    "author": "Virginia Woolf",
    "country": "United Kingdom",
    "img": "images/mrs-dalloway.jpg",
    "year": 1925,
    "pages": 216,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Mrs_Dalloway\n",
    "add_bookmark": false
  },
  {
    "id": 97,
    "title": "To the Lighthouse",
    "author": "Virginia Woolf",
    "country": "United Kingdom",
    "img": "images/to-the-lighthouse.jpg",
    "year": 1927,
    "pages": 209,
    "language": "English",
    "wikipedia_link": "https://en.wikipedia.org/wiki/To_the_Lighthouse\n",
    "add_bookmark": false
  },
  {
    "id": 98,
    "title": "Memoirs of Hadrian",
    "author": "Marguerite Yourcenar",
    "country": "France/Belgium",
    "img": "images/memoirs-of-hadrian.jpg",
    "year": 1951,
    "pages": 408,
    "language": "French",
    "wikipedia_link": "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n",
    "add_bookmark": false
  }
]